-- Contract support for the Recordatorios Supabase migration.
-- RLS is enabled in 001 and clinic-scoped policies already live in 002.

alter table public.reminders
  add column if not exists reminder_type text not null default '24h';

alter table public.reminders
  drop constraint if exists reminders_type_allowed;

alter table public.reminders
  add constraint reminders_type_allowed
  check (reminder_type in ('24h', '2h', 'immediate'));

create index if not exists reminders_clinic_id_appointment_id_idx
  on public.reminders (clinic_id, appointment_id);

create index if not exists reminders_clinic_id_status_idx
  on public.reminders (clinic_id, status);

create unique index if not exists reminders_active_type_unique_idx
  on public.reminders (clinic_id, appointment_id, reminder_type)
  where status in ('pending', 'scheduled');

comment on table public.reminders is
  'Clinic-scoped WhatsApp reminder queue. Automatic sending must be handled by backend or Edge Functions, not frontend.';

comment on column public.reminders.reminder_type is
  'Reminder timing type generated by the frontend MVP: 24h, 2h or immediate.';
